[DOCUMENTATION]
ORG_NAME="stellarhedgefunds"
ORG_DBA="From well-behaved to intact and correct nodes. Road to understanding the Stellar Consensus Protocol (SCP)"
ORG_PHYSICAL_ADDRESS="2556 Classen Blvd, Oklahoma, 73069, United States"
ORG_TWITTER="stellarhedgefunds"
ORG_GITHUB="stellarhedgefunds"
ORG_URL="https://stellar.org"
ORG_LOGO="https://stellarhedgefunds.pages.dev/images/stellarhedgefunds.jpg"
ORG_OFFICIAL_EMAIL="info@stellarhedgefunds.pages.dev"
ORG_SUPPORT_EMAIL="mail@stellarhedgefunds.pages.dev"
ORG_PHONE_NUMBER="(405) 701-0715"
ORG_DESCRIPTION="THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."



[[PRINCIPALS]]
name="Liza Parisian"
github="Crypto_Liza"
keybase="Crypto_Liza"
twitter="Crypto_Liza"
email="liza@stellarhedgefunds.pages.dev"



[[CURRENCIES]]
code="EMC"
name="Elliott Management Corporation"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/EMC.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
fixed_number=1000000000
anchor_asset="Hedge Fund"
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="MILLENNIUM"
name="Millennium Asset Management"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/MILLENNIUM.webp"
is_asset_anchored=true
anchor_asset_type="bond"
fixed_number=1000000000
anchor_asset="Hedge Fund"
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="ZIFF"
name="Och-Ziff Asset Management"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/ZIFF.webp"
is_asset_anchored=true
anchor_asset_type="bond"
fixed_number=1000000000
anchor_asset="Hedge Fund"
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="TIGER"
name="Tiger Global Management"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/TIGER.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
fixed_number=1000000000
anchor_asset="Hedge Fund"
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="MOORE"
name="Moore Capital Management"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/MOORE.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
fixed_number=1000000000
anchor_asset="Hedge Fund"
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="OAKTREE"
name="Oaktree Capital Management"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/OAKTREE.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
fixed_number=1000000000
anchor_asset="Hedge Fund"
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="BRIDGEWATER"
name="Bridgewater Associates"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/BRIDGEWATER.webp"
is_asset_anchored=true
anchor_asset_type="bond"
anchor_asset="Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="RTEC"
name="Renaissance Technologies"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/RTEC.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="2SIG"
name="2 Sigma"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/2SIG.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="CITADEL"
name="Citadel LLC"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/CITADEL.webp"
is_asset_anchored=true
anchor_asset_type="bond"
anchor_asset="Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="BRK"
name="Berkshire Hathaway"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/BRK.webp"
is_asset_anchored=true
anchor_asset_type="bond"
anchor_asset="Investment Group"
conditions="Digital Currency"
fixed_number=1000000000
status="live"

[[CURRENCIES]]
code="UBS"
name="UBS Switzerland"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/UBS.webp"
is_asset_anchored=true
anchor_asset_type="bond"
anchor_asset="Swiss Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="ACM"
name="Andurand Capital Management"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/ACM.webp"
is_asset_anchored=true
anchor_asset_type="commodity"
anchor_asset="Oil Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="SAC"
name="Point72 Capital"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/SAC.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="AQR"
name="AQR Capital Management"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/AQR.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
conditions="Digital Currency"
fixed_number=1000000000
status="live"

[[CURRENCIES]]
code="BLACKROCK"
name="BlackRock Asset Management"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/BLACKROCK.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="CARLSON"
name="Carlson Capital Management"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/CARLSON.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="CAXTON"
name="Caxton Associates"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/CAXTON.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="SHAW"
name="DE Shaw & Co."
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/SHAW.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="GAM"
name="GAM Holdings"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/GAM.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="GOLDMAN"
name="Goldman Sachs Asset Management"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/GOLDMAN.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Goldman Sachs Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="LAZARD"
name="Lazard Alternatives"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/LAZARD.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="MAVERICK"
name="Maverick Capital"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/MAVERICK.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"

[[CURRENCIES]]
code="PSQUARE"
name="PERSHING SQUARE CAPITAL"
issuer="GDCKLQ5IQTZMM56BSQO2V4TTYZNC4IVUWXYIKMRR2M7NHBUADZOSZBBC"
image="https://stellarhedgefunds.pages.dev/images/PSQUARE.webp"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
fixed_number=1000000000
conditions="Digital Currency"
status="live"
