VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"


[DOCUMENTATION]
ORG_NAME="Stellar Gold"
ORG_DBA="From well-behaved to intact and correct nodes. Road to understanding the Stellar Consensus Protocol (SCP)"
ORG_PHYSICAL_ADDRESS="2556 Classen Blvd, Oklahoma, 73069, United States"
ORG_TWITTER="stellargold"
ORG_GITHUB="stellargold"
ORG_URL="https://stellar-gold.vercel.app"
ORG_LOGO="https://stellar-gold.vercel.app/images/stellargold.png"
ORG_OFFICIAL_EMAIL="info@stellar-gold.vercel.app"
ORG_SUPPORT_EMAIL="mail@stellar-gold.vercel.app"
ORG_PHONE_NUMBER="(405) 701-0715"
ORG_DESCRIPTION="THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."



[[PRINCIPALS]]
name="Liza Parisian"
github="Crypto_Liza"
keybase="Crypto_Liza"
twitter="Crypto_Liza"
email="liza@stellar-gold.vercel.app"


[[CURRENCIES]]
code="XAUt"
name="Tether Gold"
issuer="GBFATKDC27QHR3GI6RJ46KA6MBQTSXQ5MWUSEKJQCDGO7RANYOPQ5MPG"
image="https://stellar-gold.vercel.app/images/XAUt.png"
is_asset_anchored=true
anchor_asset_type="realestate"
fixed_number=1000000000000000
anchor_asset="Hedge Fund"
status="live"
desc="Tether Gold (XAU₮) is a stablecoin that provides ownership on a 1:1 basis of one fine troy ounce of gold on a physical bar of gold that meets the Good Delivery standard of the London Bullion Market Association (LBMA). This technology allows access to a stablecoin that provides ownership of physical gold while avoiding the drawbacks associated with physical gold, such as high storage cost and limited accessibility. Note: XAU₮ tokens can be fractionated up to six decimal places (i.e. in increments as small as 0.000001 troy fine ounce)."
display_decimals=7

[[CURRENCIES]]
code="XAG"
name="SILVER"
issuer="GBFATKDC27QHR3GI6RJ46KA6MBQTSXQ5MWUSEKJQCDGO7RANYOPQ5MPG"
image="https://stellar-gold.vercel.app/images/XAG.png"
is_asset_anchored=true
anchor_asset_type="bond"
fixed_number=1000000000000000
anchor_asset="Hedge Fund"
status="live"
desc="XAG is the trading symbol for silver in the financial markets, particularly in the context of futures and spot trading. The code XAG is derived from the Latin word argentum, which means silver. It is used in various trading platforms, exchanges, and financial instruments to represent the precious metal."
display_decimals=7

[[CURRENCIES]]
code="XPD"
name="PALLDIUM"
issuer="GBFATKDC27QHR3GI6RJ46KA6MBQTSXQ5MWUSEKJQCDGO7RANYOPQ5MPG"
image="https://stellar-gold.vercel.app/images/XPD.png"
is_asset_anchored=true
anchor_asset_type="bond"
fixed_number=1000000000000000
anchor_asset="Hedge Fund"
status="live"
desc="XPD in the context of Forex (foreign exchange) refers to the trading of palladium, which is represented by the symbol XPD. It is one of the precious metals traded in the Forex market, alongside others like gold (XAU) and silver (XAG). Palladium is a rare metal primarily used in automotive catalytic converters, electronics, and jewelry, making its price subject to various economic factors, including industrial demand and supply constraints."
display_decimals=7

[[CURRENCIES]]
code="XPT"
name="PLATINUM"
issuer="GBFATKDC27QHR3GI6RJ46KA6MBQTSXQ5MWUSEKJQCDGO7RANYOPQ5MPG"
image="https://stellar-gold.vercel.app/images/XPT.png"
is_asset_anchored=true
anchor_asset_type="realestate"
fixed_number=1000000000000000
anchor_asset="Hedge Fund"
status="live"
desc="In the context of Forex (foreign exchange), XPT refers to the currency code for platinum. It is part of the ISO 4217 standard, which assigns three-letter codes to currencies and precious metals. Platinum is a precious metal that is often traded as a commodity, similar to gold and silver, and its price can be influenced by various factors including supply and demand dynamics, industrial usage, and macroeconomic conditions."
display_decimals=7

[[CURRENCIES]]
code="XCU"
name="COPPER"
issuer="GBFATKDC27QHR3GI6RJ46KA6MBQTSXQ5MWUSEKJQCDGO7RANYOPQ5MPG"
image="https://stellar-gold.vercel.app/images/XCU.png"
is_asset_anchored=true
anchor_asset_type="realestate"
fixed_number=1000000000000000
anchor_asset="Hedge Fund"
status="live"
desc="XCU is not a commonly used term in Forex trading or foreign exchange markets. However, it can refer to a specific currency pair or market notation that may be used by certain traders or platforms. In the context of Forex, traders usually refer to currency pairs (like EUR/USD, GBP/JPY, etc.), commodities, or other financial instruments."
display_decimals=7

[[CURRENCIES]]
code="XZN"
name="ZINC"
issuer="GBFATKDC27QHR3GI6RJ46KA6MBQTSXQ5MWUSEKJQCDGO7RANYOPQ5MPG"
image="https://stellar-gold.vercel.app/images/XZN.png"
is_asset_anchored=true
anchor_asset_type="realestate"
fixed_number=1000000000000000
anchor_asset="Hedge Fund"
status="live"
desc="In the context of Forex (foreign exchange) trading, XZN does not refer to a widely recognized currency pair or trading term. It is possible that XZN might be a typographical error or a misunderstanding of a more common currency code."
display_decimals=7

[[CURRENCIES]]
code="XNI"
name="NICKEL"
issuer="GBFATKDC27QHR3GI6RJ46KA6MBQTSXQ5MWUSEKJQCDGO7RANYOPQ5MPG"
image="https://stellar-gold.vercel.app/images/XNI.png"
is_asset_anchored=true
anchor_asset_type="bond"
anchor_asset="Hedge Fund"
fixed_number=1000000000000000
status="live"
desc="XNI is not a common term in the Forex market. However, depending on the context, it may refer to different concepts. It can be a specific financial instrument, trading strategy, or even a currency code in certain contexts. Which is launched at a reasonable price for Stellar Lumens"
display_decimals=7

[[CURRENCIES]]
code="XPB"
name="LEAD"
issuer="GBFATKDC27QHR3GI6RJ46KA6MBQTSXQ5MWUSEKJQCDGO7RANYOPQ5MPG"
image="https://stellar-gold.vercel.app/images/XPB.png"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
fixed_number=1000000000000000
status="live"
desc="In the context of Forex trading, “XPB” usually refers to the currency pair that represents the price of the British Pound (GBP) against the Euro (EUR). However, it is important to note that “XPB” can also refer to specific trading instruments or products, depending on the broker or trading platform. We trade Stellar as the XPB/XLM currency pair on the Stellar platform."
display_decimals=7

[[CURRENCIES]]
code="WTI"
name="West Texas Intermediate"
issuer="GBFATKDC27QHR3GI6RJ46KA6MBQTSXQ5MWUSEKJQCDGO7RANYOPQ5MPG"
image="https://stellar-gold.vercel.app/images/WTI.png"
is_asset_anchored=true
anchor_asset_type="realestate"
anchor_asset="Hedge Fund"
fixed_number=1000000000000000
status="live"
desc="WTI, or West Texas Intermediate, is a grade of crude oil used as a benchmark in oil pricing. In the context of forex trading, WTI is important because the price of oil can have a significant impact on currency values, especially for countries that are major producers or consumers of oil. You can trade oil with Stellar"
display_decimals=7

[[CURRENCIES]]
code="NG"
name="Natural Gas"
issuer="GBFATKDC27QHR3GI6RJ46KA6MBQTSXQ5MWUSEKJQCDGO7RANYOPQ5MPG"
image="https://stellar-gold.vercel.app/images/NG.png"
is_asset_anchored=true
anchor_asset_type="bond"
anchor_asset="Hedge Fund"
fixed_number=1000000000000000
status="live"
desc="In the context of forex (foreign exchange) trading, NG typically refers to Natural Gas rather than a currency pair or forex-specific term. Natural gas is a significant commodity in global markets, and its trading can be influenced by various factors, including supply and demand dynamics, weather conditions, geopolitical events, and economic data."
display_decimals=7

[[CURRENCIES]]
code="BRENT"
name="Brent Crude Oil"
issuer="GBFATKDC27QHR3GI6RJ46KA6MBQTSXQ5MWUSEKJQCDGO7RANYOPQ5MPG"
image="https://stellar-gold.vercel.app/images/BRENT.png"
is_asset_anchored=true
anchor_asset_type="bond"
anchor_asset="Investment Group"
fixed_number=1000000000000000
status="live"
desc="In the context of forex trading, BRENT usually refers to Brent crude oil, which is one of the main benchmarks for global oil prices. Understanding Brent crude oil is essential for forex traders, especially those who focus on the currencies of oil-exporting and oil-importing countries.Make Money Trading Oil"
display_decimals=7

[[CURRENCIES]]
code="XLMG"
name="Stellar Gold"
issuer="GBFATKDC27QHR3GI6RJ46KA6MBQTSXQ5MWUSEKJQCDGO7RANYOPQ5MPG"
image="https://stellar-gold.vercel.app/imges/XLMG.png"
is_asset_anchored=true
anchor_asset_type="bond"
anchor_asset="Investment Group"
fixed_number=1000000000000000
status="live"
desc="Join XLMG and XLMS staking program today stake.stellargold.net and receive upto 22% APY staking rewards. Rewards are being paid weekly. More info in telegram group @officialXLMG"
display_decimals=7

[[CURRENCIES]]
code="XLMS"
name="Stellar Silver"
issuer="GBFATKDC27QHR3GI6RJ46KA6MBQTSXQ5MWUSEKJQCDGO7RANYOPQ5MPG"
image="https://stellar-gold.vercel.app/imges/XLMS.png"
is_asset_anchored = true
anchor_asset_type="bond"
anchor_asset="Investment Group"
fixed_number=1000000000000000
status="live"
desc="Stellar Silver is New token created for liquidity pool and to reward XLMG holders with rewards on weekly basis and upto 0.42% weekly APY based on your holdings."
display_decimals=7
